version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static  # django 컨테이너의 static 폴더를 공유
    ports:
      - "8000:8000"  # Django 내부 포트
    env_file:
      - .env
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 외부에서 80번 포트로 접근
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
    depends_on:
      - django

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} --databases 16
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  static: